# Generated by Django 5.0.4 on 2024-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0002_alter_achat_clef_achat_alter_achat_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='clef_unique',
            field=models.CharField(default='kPeSSna9r0zaGHBO', max_length=16, unique=True),
        ),
    ]
